version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.3-browsers
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: run tests
          command: npm test